### ISSUE TITLE
GTF file

### ISSUE THREAD

**Issue by JohnHellgren** [AbeelLab/nanopore-cenpk113-7d#1]
Hello,

Do you by any chance have a GTF file for the annotations as well?
Or do you know any good way for converting between GFF and GTF?

Kind regards,
John Hellgren

**Comment by thomasabeel** [comment]
GTF is a more strict format and I don't have a good way to convert from GFF to GTF. 

I did have a script that claims to do the job, but I have no way to verify whether the output is in fact GTF compliant.

Have a look:
[CENPK113-7D_20170627.gtf.zip](https://github.com/AbeelLab/nanopore-cenpk113-7d/files/1567699/CENPK113-7D_20170627.gtf.zip)
